// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraData.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CameraData.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace camera {
class CameraDataDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CameraData> {
} _CameraData_default_instance_;
class CameraOrderDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CameraOrder> {
} _CameraOrder_default_instance_;

namespace protobuf_CameraData_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, origin_width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, origin_height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, compressed_width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, compressed_height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, camera_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, recording_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, showing_ae_roi_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraData, byte_buffer_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, camera_request_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, show_ae_roi_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, forward_narrow_start_recording_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, forward_wide_start_recording_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, backward_narrow_start_recording_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, left_start_recording_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, right_start_recording_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraOrder, interior_start_recording_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CameraData)},
  { 12, -1, sizeof(CameraOrder)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CameraData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_CameraOrder_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "CameraData.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _CameraData_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _CameraOrder_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CameraData_default_instance_.DefaultConstruct();
  _CameraOrder_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\020CameraData.proto\022\006camera\"\323\001\n\nCameraDat"
      "a\022\024\n\014origin_width\030\001 \001(\005\022\025\n\rorigin_height"
      "\030\002 \001(\005\022\030\n\020compressed_width\030\003 \001(\005\022\031\n\021comp"
      "ressed_height\030\004 \001(\005\022#\n\006camera\030\005 \001(\0162\023.ca"
      "mera.camera_type\022\021\n\trecording\030\006 \001(\010\022\026\n\016s"
      "howing_AE_ROI\030\007 \001(\010\022\023\n\013byte_buffer\030\010 \001(\014"
      "\"\245\002\n\013CameraOrder\022+\n\016camera_request\030\001 \001(\016"
      "2\023.camera.camera_type\022\023\n\013show_AE_ROI\030\002 \001"
      "(\010\022&\n\036forward_narrow_start_recording\030\025 \001"
      "(\010\022$\n\034forward_wide_start_recording\030\026 \001(\010"
      "\022\'\n\037backward_narrow_start_recording\030\027 \001("
      "\010\022\034\n\024left_start_recording\030\030 \001(\010\022\035\n\025right"
      "_start_recording\030\031 \001(\010\022 \n\030interior_start"
      "_recording\030\032 \001(\010*k\n\013camera_type\022\022\n\016forwa"
      "rd_narrow\020\000\022\020\n\014forward_wide\020\001\022\023\n\017backwar"
      "d_narrow\020\002\022\010\n\004left\020\003\022\t\n\005right\020\004\022\014\n\010inter"
      "ior\020\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 653);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CameraData.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_CameraData_2eproto

const ::google::protobuf::EnumDescriptor* camera_type_descriptor() {
  protobuf_CameraData_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CameraData_2eproto::file_level_enum_descriptors[0];
}
bool camera_type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CameraData::kOriginWidthFieldNumber;
const int CameraData::kOriginHeightFieldNumber;
const int CameraData::kCompressedWidthFieldNumber;
const int CameraData::kCompressedHeightFieldNumber;
const int CameraData::kCameraFieldNumber;
const int CameraData::kRecordingFieldNumber;
const int CameraData::kShowingAEROIFieldNumber;
const int CameraData::kByteBufferFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CameraData::CameraData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_CameraData_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera.CameraData)
}
CameraData::CameraData(const CameraData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  byte_buffer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.byte_buffer().size() > 0) {
    byte_buffer_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.byte_buffer_);
  }
  ::memcpy(&origin_width_, &from.origin_width_,
    reinterpret_cast<char*>(&showing_ae_roi_) -
    reinterpret_cast<char*>(&origin_width_) + sizeof(showing_ae_roi_));
  // @@protoc_insertion_point(copy_constructor:camera.CameraData)
}

void CameraData::SharedCtor() {
  byte_buffer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&origin_width_, 0, reinterpret_cast<char*>(&showing_ae_roi_) -
    reinterpret_cast<char*>(&origin_width_) + sizeof(showing_ae_roi_));
  _cached_size_ = 0;
}

CameraData::~CameraData() {
  // @@protoc_insertion_point(destructor:camera.CameraData)
  SharedDtor();
}

void CameraData::SharedDtor() {
  byte_buffer_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CameraData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CameraData::descriptor() {
  protobuf_CameraData_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CameraData_2eproto::file_level_metadata[0].descriptor;
}

const CameraData& CameraData::default_instance() {
  protobuf_CameraData_2eproto::InitDefaults();
  return *internal_default_instance();
}

CameraData* CameraData::New(::google::protobuf::Arena* arena) const {
  CameraData* n = new CameraData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CameraData::Clear() {
// @@protoc_insertion_point(message_clear_start:camera.CameraData)
  byte_buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&origin_width_, 0, reinterpret_cast<char*>(&showing_ae_roi_) -
    reinterpret_cast<char*>(&origin_width_) + sizeof(showing_ae_roi_));
}

bool CameraData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera.CameraData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 origin_width = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &origin_width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 origin_height = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &origin_height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 compressed_width = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &compressed_width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 compressed_height = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &compressed_height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .camera.camera_type camera = 5;
      case 5: {
        if (tag == 40u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_camera(static_cast< ::camera::camera_type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool recording = 6;
      case 6: {
        if (tag == 48u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &recording_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool showing_AE_ROI = 7;
      case 7: {
        if (tag == 56u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &showing_ae_roi_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes byte_buffer = 8;
      case 8: {
        if (tag == 66u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_byte_buffer()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera.CameraData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera.CameraData)
  return false;
#undef DO_
}

void CameraData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera.CameraData)
  // int32 origin_width = 1;
  if (this->origin_width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->origin_width(), output);
  }

  // int32 origin_height = 2;
  if (this->origin_height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->origin_height(), output);
  }

  // int32 compressed_width = 3;
  if (this->compressed_width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->compressed_width(), output);
  }

  // int32 compressed_height = 4;
  if (this->compressed_height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->compressed_height(), output);
  }

  // .camera.camera_type camera = 5;
  if (this->camera() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->camera(), output);
  }

  // bool recording = 6;
  if (this->recording() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->recording(), output);
  }

  // bool showing_AE_ROI = 7;
  if (this->showing_ae_roi() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->showing_ae_roi(), output);
  }

  // bytes byte_buffer = 8;
  if (this->byte_buffer().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      8, this->byte_buffer(), output);
  }

  // @@protoc_insertion_point(serialize_end:camera.CameraData)
}

::google::protobuf::uint8* CameraData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:camera.CameraData)
  // int32 origin_width = 1;
  if (this->origin_width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->origin_width(), target);
  }

  // int32 origin_height = 2;
  if (this->origin_height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->origin_height(), target);
  }

  // int32 compressed_width = 3;
  if (this->compressed_width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->compressed_width(), target);
  }

  // int32 compressed_height = 4;
  if (this->compressed_height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->compressed_height(), target);
  }

  // .camera.camera_type camera = 5;
  if (this->camera() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->camera(), target);
  }

  // bool recording = 6;
  if (this->recording() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->recording(), target);
  }

  // bool showing_AE_ROI = 7;
  if (this->showing_ae_roi() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->showing_ae_roi(), target);
  }

  // bytes byte_buffer = 8;
  if (this->byte_buffer().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        8, this->byte_buffer(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:camera.CameraData)
  return target;
}

size_t CameraData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera.CameraData)
  size_t total_size = 0;

  // bytes byte_buffer = 8;
  if (this->byte_buffer().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->byte_buffer());
  }

  // int32 origin_width = 1;
  if (this->origin_width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->origin_width());
  }

  // int32 origin_height = 2;
  if (this->origin_height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->origin_height());
  }

  // int32 compressed_width = 3;
  if (this->compressed_width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->compressed_width());
  }

  // int32 compressed_height = 4;
  if (this->compressed_height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->compressed_height());
  }

  // .camera.camera_type camera = 5;
  if (this->camera() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->camera());
  }

  // bool recording = 6;
  if (this->recording() != 0) {
    total_size += 1 + 1;
  }

  // bool showing_AE_ROI = 7;
  if (this->showing_ae_roi() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CameraData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera.CameraData)
  GOOGLE_DCHECK_NE(&from, this);
  const CameraData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CameraData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera.CameraData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera.CameraData)
    MergeFrom(*source);
  }
}

void CameraData::MergeFrom(const CameraData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera.CameraData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.byte_buffer().size() > 0) {

    byte_buffer_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.byte_buffer_);
  }
  if (from.origin_width() != 0) {
    set_origin_width(from.origin_width());
  }
  if (from.origin_height() != 0) {
    set_origin_height(from.origin_height());
  }
  if (from.compressed_width() != 0) {
    set_compressed_width(from.compressed_width());
  }
  if (from.compressed_height() != 0) {
    set_compressed_height(from.compressed_height());
  }
  if (from.camera() != 0) {
    set_camera(from.camera());
  }
  if (from.recording() != 0) {
    set_recording(from.recording());
  }
  if (from.showing_ae_roi() != 0) {
    set_showing_ae_roi(from.showing_ae_roi());
  }
}

void CameraData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera.CameraData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraData::CopyFrom(const CameraData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera.CameraData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraData::IsInitialized() const {
  return true;
}

void CameraData::Swap(CameraData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CameraData::InternalSwap(CameraData* other) {
  byte_buffer_.Swap(&other->byte_buffer_);
  std::swap(origin_width_, other->origin_width_);
  std::swap(origin_height_, other->origin_height_);
  std::swap(compressed_width_, other->compressed_width_);
  std::swap(compressed_height_, other->compressed_height_);
  std::swap(camera_, other->camera_);
  std::swap(recording_, other->recording_);
  std::swap(showing_ae_roi_, other->showing_ae_roi_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CameraData::GetMetadata() const {
  protobuf_CameraData_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CameraData_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CameraData

// int32 origin_width = 1;
void CameraData::clear_origin_width() {
  origin_width_ = 0;
}
::google::protobuf::int32 CameraData::origin_width() const {
  // @@protoc_insertion_point(field_get:camera.CameraData.origin_width)
  return origin_width_;
}
void CameraData::set_origin_width(::google::protobuf::int32 value) {
  
  origin_width_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraData.origin_width)
}

// int32 origin_height = 2;
void CameraData::clear_origin_height() {
  origin_height_ = 0;
}
::google::protobuf::int32 CameraData::origin_height() const {
  // @@protoc_insertion_point(field_get:camera.CameraData.origin_height)
  return origin_height_;
}
void CameraData::set_origin_height(::google::protobuf::int32 value) {
  
  origin_height_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraData.origin_height)
}

// int32 compressed_width = 3;
void CameraData::clear_compressed_width() {
  compressed_width_ = 0;
}
::google::protobuf::int32 CameraData::compressed_width() const {
  // @@protoc_insertion_point(field_get:camera.CameraData.compressed_width)
  return compressed_width_;
}
void CameraData::set_compressed_width(::google::protobuf::int32 value) {
  
  compressed_width_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraData.compressed_width)
}

// int32 compressed_height = 4;
void CameraData::clear_compressed_height() {
  compressed_height_ = 0;
}
::google::protobuf::int32 CameraData::compressed_height() const {
  // @@protoc_insertion_point(field_get:camera.CameraData.compressed_height)
  return compressed_height_;
}
void CameraData::set_compressed_height(::google::protobuf::int32 value) {
  
  compressed_height_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraData.compressed_height)
}

// .camera.camera_type camera = 5;
void CameraData::clear_camera() {
  camera_ = 0;
}
::camera::camera_type CameraData::camera() const {
  // @@protoc_insertion_point(field_get:camera.CameraData.camera)
  return static_cast< ::camera::camera_type >(camera_);
}
void CameraData::set_camera(::camera::camera_type value) {
  
  camera_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraData.camera)
}

// bool recording = 6;
void CameraData::clear_recording() {
  recording_ = false;
}
bool CameraData::recording() const {
  // @@protoc_insertion_point(field_get:camera.CameraData.recording)
  return recording_;
}
void CameraData::set_recording(bool value) {
  
  recording_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraData.recording)
}

// bool showing_AE_ROI = 7;
void CameraData::clear_showing_ae_roi() {
  showing_ae_roi_ = false;
}
bool CameraData::showing_ae_roi() const {
  // @@protoc_insertion_point(field_get:camera.CameraData.showing_AE_ROI)
  return showing_ae_roi_;
}
void CameraData::set_showing_ae_roi(bool value) {
  
  showing_ae_roi_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraData.showing_AE_ROI)
}

// bytes byte_buffer = 8;
void CameraData::clear_byte_buffer() {
  byte_buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CameraData::byte_buffer() const {
  // @@protoc_insertion_point(field_get:camera.CameraData.byte_buffer)
  return byte_buffer_.GetNoArena();
}
void CameraData::set_byte_buffer(const ::std::string& value) {
  
  byte_buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:camera.CameraData.byte_buffer)
}
#if LANG_CXX11
void CameraData::set_byte_buffer(::std::string&& value) {
  
  byte_buffer_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:camera.CameraData.byte_buffer)
}
#endif
void CameraData::set_byte_buffer(const char* value) {
  
  byte_buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:camera.CameraData.byte_buffer)
}
void CameraData::set_byte_buffer(const void* value, size_t size) {
  
  byte_buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:camera.CameraData.byte_buffer)
}
::std::string* CameraData::mutable_byte_buffer() {
  
  // @@protoc_insertion_point(field_mutable:camera.CameraData.byte_buffer)
  return byte_buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CameraData::release_byte_buffer() {
  // @@protoc_insertion_point(field_release:camera.CameraData.byte_buffer)
  
  return byte_buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CameraData::set_allocated_byte_buffer(::std::string* byte_buffer) {
  if (byte_buffer != NULL) {
    
  } else {
    
  }
  byte_buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), byte_buffer);
  // @@protoc_insertion_point(field_set_allocated:camera.CameraData.byte_buffer)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CameraOrder::kCameraRequestFieldNumber;
const int CameraOrder::kShowAEROIFieldNumber;
const int CameraOrder::kForwardNarrowStartRecordingFieldNumber;
const int CameraOrder::kForwardWideStartRecordingFieldNumber;
const int CameraOrder::kBackwardNarrowStartRecordingFieldNumber;
const int CameraOrder::kLeftStartRecordingFieldNumber;
const int CameraOrder::kRightStartRecordingFieldNumber;
const int CameraOrder::kInteriorStartRecordingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CameraOrder::CameraOrder()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_CameraData_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:camera.CameraOrder)
}
CameraOrder::CameraOrder(const CameraOrder& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&camera_request_, &from.camera_request_,
    reinterpret_cast<char*>(&interior_start_recording_) -
    reinterpret_cast<char*>(&camera_request_) + sizeof(interior_start_recording_));
  // @@protoc_insertion_point(copy_constructor:camera.CameraOrder)
}

void CameraOrder::SharedCtor() {
  ::memset(&camera_request_, 0, reinterpret_cast<char*>(&interior_start_recording_) -
    reinterpret_cast<char*>(&camera_request_) + sizeof(interior_start_recording_));
  _cached_size_ = 0;
}

CameraOrder::~CameraOrder() {
  // @@protoc_insertion_point(destructor:camera.CameraOrder)
  SharedDtor();
}

void CameraOrder::SharedDtor() {
}

void CameraOrder::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CameraOrder::descriptor() {
  protobuf_CameraData_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CameraData_2eproto::file_level_metadata[1].descriptor;
}

const CameraOrder& CameraOrder::default_instance() {
  protobuf_CameraData_2eproto::InitDefaults();
  return *internal_default_instance();
}

CameraOrder* CameraOrder::New(::google::protobuf::Arena* arena) const {
  CameraOrder* n = new CameraOrder;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CameraOrder::Clear() {
// @@protoc_insertion_point(message_clear_start:camera.CameraOrder)
  ::memset(&camera_request_, 0, reinterpret_cast<char*>(&interior_start_recording_) -
    reinterpret_cast<char*>(&camera_request_) + sizeof(interior_start_recording_));
}

bool CameraOrder::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:camera.CameraOrder)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .camera.camera_type camera_request = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_camera_request(static_cast< ::camera::camera_type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool show_AE_ROI = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &show_ae_roi_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool forward_narrow_start_recording = 21;
      case 21: {
        if (tag == 168u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &forward_narrow_start_recording_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool forward_wide_start_recording = 22;
      case 22: {
        if (tag == 176u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &forward_wide_start_recording_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool backward_narrow_start_recording = 23;
      case 23: {
        if (tag == 184u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &backward_narrow_start_recording_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool left_start_recording = 24;
      case 24: {
        if (tag == 192u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &left_start_recording_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool right_start_recording = 25;
      case 25: {
        if (tag == 200u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &right_start_recording_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool interior_start_recording = 26;
      case 26: {
        if (tag == 208u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &interior_start_recording_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:camera.CameraOrder)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:camera.CameraOrder)
  return false;
#undef DO_
}

void CameraOrder::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:camera.CameraOrder)
  // .camera.camera_type camera_request = 1;
  if (this->camera_request() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->camera_request(), output);
  }

  // bool show_AE_ROI = 2;
  if (this->show_ae_roi() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->show_ae_roi(), output);
  }

  // bool forward_narrow_start_recording = 21;
  if (this->forward_narrow_start_recording() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(21, this->forward_narrow_start_recording(), output);
  }

  // bool forward_wide_start_recording = 22;
  if (this->forward_wide_start_recording() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(22, this->forward_wide_start_recording(), output);
  }

  // bool backward_narrow_start_recording = 23;
  if (this->backward_narrow_start_recording() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(23, this->backward_narrow_start_recording(), output);
  }

  // bool left_start_recording = 24;
  if (this->left_start_recording() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(24, this->left_start_recording(), output);
  }

  // bool right_start_recording = 25;
  if (this->right_start_recording() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(25, this->right_start_recording(), output);
  }

  // bool interior_start_recording = 26;
  if (this->interior_start_recording() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(26, this->interior_start_recording(), output);
  }

  // @@protoc_insertion_point(serialize_end:camera.CameraOrder)
}

::google::protobuf::uint8* CameraOrder::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:camera.CameraOrder)
  // .camera.camera_type camera_request = 1;
  if (this->camera_request() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->camera_request(), target);
  }

  // bool show_AE_ROI = 2;
  if (this->show_ae_roi() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->show_ae_roi(), target);
  }

  // bool forward_narrow_start_recording = 21;
  if (this->forward_narrow_start_recording() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(21, this->forward_narrow_start_recording(), target);
  }

  // bool forward_wide_start_recording = 22;
  if (this->forward_wide_start_recording() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(22, this->forward_wide_start_recording(), target);
  }

  // bool backward_narrow_start_recording = 23;
  if (this->backward_narrow_start_recording() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(23, this->backward_narrow_start_recording(), target);
  }

  // bool left_start_recording = 24;
  if (this->left_start_recording() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(24, this->left_start_recording(), target);
  }

  // bool right_start_recording = 25;
  if (this->right_start_recording() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(25, this->right_start_recording(), target);
  }

  // bool interior_start_recording = 26;
  if (this->interior_start_recording() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(26, this->interior_start_recording(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:camera.CameraOrder)
  return target;
}

size_t CameraOrder::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:camera.CameraOrder)
  size_t total_size = 0;

  // .camera.camera_type camera_request = 1;
  if (this->camera_request() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->camera_request());
  }

  // bool show_AE_ROI = 2;
  if (this->show_ae_roi() != 0) {
    total_size += 1 + 1;
  }

  // bool forward_narrow_start_recording = 21;
  if (this->forward_narrow_start_recording() != 0) {
    total_size += 2 + 1;
  }

  // bool forward_wide_start_recording = 22;
  if (this->forward_wide_start_recording() != 0) {
    total_size += 2 + 1;
  }

  // bool backward_narrow_start_recording = 23;
  if (this->backward_narrow_start_recording() != 0) {
    total_size += 2 + 1;
  }

  // bool left_start_recording = 24;
  if (this->left_start_recording() != 0) {
    total_size += 2 + 1;
  }

  // bool right_start_recording = 25;
  if (this->right_start_recording() != 0) {
    total_size += 2 + 1;
  }

  // bool interior_start_recording = 26;
  if (this->interior_start_recording() != 0) {
    total_size += 2 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CameraOrder::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:camera.CameraOrder)
  GOOGLE_DCHECK_NE(&from, this);
  const CameraOrder* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CameraOrder>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:camera.CameraOrder)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:camera.CameraOrder)
    MergeFrom(*source);
  }
}

void CameraOrder::MergeFrom(const CameraOrder& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:camera.CameraOrder)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.camera_request() != 0) {
    set_camera_request(from.camera_request());
  }
  if (from.show_ae_roi() != 0) {
    set_show_ae_roi(from.show_ae_roi());
  }
  if (from.forward_narrow_start_recording() != 0) {
    set_forward_narrow_start_recording(from.forward_narrow_start_recording());
  }
  if (from.forward_wide_start_recording() != 0) {
    set_forward_wide_start_recording(from.forward_wide_start_recording());
  }
  if (from.backward_narrow_start_recording() != 0) {
    set_backward_narrow_start_recording(from.backward_narrow_start_recording());
  }
  if (from.left_start_recording() != 0) {
    set_left_start_recording(from.left_start_recording());
  }
  if (from.right_start_recording() != 0) {
    set_right_start_recording(from.right_start_recording());
  }
  if (from.interior_start_recording() != 0) {
    set_interior_start_recording(from.interior_start_recording());
  }
}

void CameraOrder::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:camera.CameraOrder)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraOrder::CopyFrom(const CameraOrder& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:camera.CameraOrder)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraOrder::IsInitialized() const {
  return true;
}

void CameraOrder::Swap(CameraOrder* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CameraOrder::InternalSwap(CameraOrder* other) {
  std::swap(camera_request_, other->camera_request_);
  std::swap(show_ae_roi_, other->show_ae_roi_);
  std::swap(forward_narrow_start_recording_, other->forward_narrow_start_recording_);
  std::swap(forward_wide_start_recording_, other->forward_wide_start_recording_);
  std::swap(backward_narrow_start_recording_, other->backward_narrow_start_recording_);
  std::swap(left_start_recording_, other->left_start_recording_);
  std::swap(right_start_recording_, other->right_start_recording_);
  std::swap(interior_start_recording_, other->interior_start_recording_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CameraOrder::GetMetadata() const {
  protobuf_CameraData_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CameraData_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CameraOrder

// .camera.camera_type camera_request = 1;
void CameraOrder::clear_camera_request() {
  camera_request_ = 0;
}
::camera::camera_type CameraOrder::camera_request() const {
  // @@protoc_insertion_point(field_get:camera.CameraOrder.camera_request)
  return static_cast< ::camera::camera_type >(camera_request_);
}
void CameraOrder::set_camera_request(::camera::camera_type value) {
  
  camera_request_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraOrder.camera_request)
}

// bool show_AE_ROI = 2;
void CameraOrder::clear_show_ae_roi() {
  show_ae_roi_ = false;
}
bool CameraOrder::show_ae_roi() const {
  // @@protoc_insertion_point(field_get:camera.CameraOrder.show_AE_ROI)
  return show_ae_roi_;
}
void CameraOrder::set_show_ae_roi(bool value) {
  
  show_ae_roi_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraOrder.show_AE_ROI)
}

// bool forward_narrow_start_recording = 21;
void CameraOrder::clear_forward_narrow_start_recording() {
  forward_narrow_start_recording_ = false;
}
bool CameraOrder::forward_narrow_start_recording() const {
  // @@protoc_insertion_point(field_get:camera.CameraOrder.forward_narrow_start_recording)
  return forward_narrow_start_recording_;
}
void CameraOrder::set_forward_narrow_start_recording(bool value) {
  
  forward_narrow_start_recording_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraOrder.forward_narrow_start_recording)
}

// bool forward_wide_start_recording = 22;
void CameraOrder::clear_forward_wide_start_recording() {
  forward_wide_start_recording_ = false;
}
bool CameraOrder::forward_wide_start_recording() const {
  // @@protoc_insertion_point(field_get:camera.CameraOrder.forward_wide_start_recording)
  return forward_wide_start_recording_;
}
void CameraOrder::set_forward_wide_start_recording(bool value) {
  
  forward_wide_start_recording_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraOrder.forward_wide_start_recording)
}

// bool backward_narrow_start_recording = 23;
void CameraOrder::clear_backward_narrow_start_recording() {
  backward_narrow_start_recording_ = false;
}
bool CameraOrder::backward_narrow_start_recording() const {
  // @@protoc_insertion_point(field_get:camera.CameraOrder.backward_narrow_start_recording)
  return backward_narrow_start_recording_;
}
void CameraOrder::set_backward_narrow_start_recording(bool value) {
  
  backward_narrow_start_recording_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraOrder.backward_narrow_start_recording)
}

// bool left_start_recording = 24;
void CameraOrder::clear_left_start_recording() {
  left_start_recording_ = false;
}
bool CameraOrder::left_start_recording() const {
  // @@protoc_insertion_point(field_get:camera.CameraOrder.left_start_recording)
  return left_start_recording_;
}
void CameraOrder::set_left_start_recording(bool value) {
  
  left_start_recording_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraOrder.left_start_recording)
}

// bool right_start_recording = 25;
void CameraOrder::clear_right_start_recording() {
  right_start_recording_ = false;
}
bool CameraOrder::right_start_recording() const {
  // @@protoc_insertion_point(field_get:camera.CameraOrder.right_start_recording)
  return right_start_recording_;
}
void CameraOrder::set_right_start_recording(bool value) {
  
  right_start_recording_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraOrder.right_start_recording)
}

// bool interior_start_recording = 26;
void CameraOrder::clear_interior_start_recording() {
  interior_start_recording_ = false;
}
bool CameraOrder::interior_start_recording() const {
  // @@protoc_insertion_point(field_get:camera.CameraOrder.interior_start_recording)
  return interior_start_recording_;
}
void CameraOrder::set_interior_start_recording(bool value) {
  
  interior_start_recording_ = value;
  // @@protoc_insertion_point(field_set:camera.CameraOrder.interior_start_recording)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace camera

// @@protoc_insertion_point(global_scope)
